config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "sanctionable_entities#index"
  
  resources :sanctionable_entities
  resources :users, only: [:index]

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :sanctions, only: [] do
        collection { post :check_persons }
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sanctionable_entity.rb
class SanctionableEntity < ActiveRecord::Base
  validates :list_name, presence: true
  validates :official_id, presence: true
  validates :extra, presence: true

  has_many :fingerprints, class_name: 'SanctionableEntityFingerprint', dependent: :delete_all
end

app/models/sanctionable_entity_fingerprint.rb
class SanctionableEntityFingerprint < ApplicationRecord
  belongs_to :sanctionable_entity

  scope :by_fingerprints, ->(fingerprints) { fingerprints.map { |f| by_fingerprint(f) }.reduce(&:or) }
  scope :by_fingerprint, ->(fingerprint) { where("starts_with(fingerprint, ?)", fingerprint) }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController
  include ApiErrorHandling

  skip_before_action :verify_authenticity_token

  def authenticate_external_app
    if request.headers["HTTP_APP_SECRET"].blank?
      raise Error::Internal::AppSecretNotReceived
    end

    if Settings.external_app.external_app_to_test_app_secret.blank?
      raise Error::Internal::MissingAppSecretSettingsKey
    end

    if Settings.external_app.external_app_to_test_app_secret != request.headers["HTTP_APP_SECRET"]
      raise Error::Internal::ExternalAppSecretInvalid
    end
  end
end

app/controllers/api/v1/sanctions_controller.rb
class Api::V1::SanctionsController < Api::V1::BaseController
  before_action :authenticate_external_app

  REQUIRED_FIELDS = %w(list_of_persons meta)

  def check_persons
    check_required_fields

    render json: {
      data: {
        results_of_verification: Verifier.new(data).run,
        client_id: data["meta"]["client_id"].to_s
      }
    }      
  end

  private

  def check_required_fields
    missing_fields = REQUIRED_FIELDS.select { |field| data[field].blank? }
    raise Error::Internal::MissingRequiredFields.new(missing_fields) unless missing_fields.empty?
    raise Error::Internal::ListOfPersonsLimitExceeded.new if data[:list_of_persons].size > 100
    check_person_fields(data[:list_of_persons])
  end

  def check_person_fields (list_of_persons)
    list_of_persons.each do |person|
      fields_to_check = person[:fields_to_check]

      if fields_to_check.empty?
        raise Error::Internal::MissingRequiredFields.new
      end

      if (check_include_only(fields_to_check, ["full_name"])) ||
        check_include_only(fields_to_check, ["full_name", "date_of_birth"]) ||
        check_include_only(fields_to_check, ["full_name", "date_of_birth", "citizenship"]) ||
        check_include_only(fields_to_check, ["full_name", "date_of_birth", "citizenship", "gender"])
        raise Error::Internal::MissingRequiredFields.new(["full_name", "date_of_birth", "citizenship", "gender"])
      end
    end
  end

  def check_include_only(fields_to_check, required_fields)
    if fields_to_check.size != required_fields.size
      return false
    end

    required_fields.each do |field|
      if fields_to_check.include? field
        return false
      end
    end

    return true
  end

  def data
    @data ||= params.to_unsafe_h[:data]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/api_error_handling.rb
module ApiErrorHandling
  extend ActiveSupport::Concern

  included do
    rescue_from Exception,           with: :handle_internal_server_error
    rescue_from Error::TestAppError, with: :handle_api_exception
  end

  private

  def handle_api_exception(error)
    hash = error.hash_with_params(params)
    render json: hash.to_json, status: error.status
  end

  def handle_internal_server_error(original_exception)
    error = Error::External::InternalServerError.new
    notify_airbrake(original_exception)

    @error_message = original_exception.message
    @error_class   = original_exception.class.to_s

    handle_api_exception(error)
  end
end

app/controllers/sanctionable_entities_controller.rb
class SanctionableEntitiesController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  skip_before_action :verify_authenticity_token
  def index
    @sanctionable_entities = SanctionableEntity.all
    @sanctionable_entities = SanctionableEntity.paginate(page: params[:page], per_page: 50)
  end

  def show
    @sanctionable_entity = SanctionableEntity.find(params[:id])
  end

  def new
    @sanctionable_entity = SanctionableEntity.new
  end

  def create
    sanctionable_entity = SanctionableEntity.new(
      sanctionable_entity_params.merge(
        creator_id: current_user.id,
        updater_id: current_user.id,
        extra:      sanctionable_entity_extra
      )
    )
    sanctionable_entity.fingerprints = FingerprintBuilder.for_entry(sanctionable_entity)
    sanctionable_entity.save!

    redirect_to :sanctionable_entities
  end

  def edit
    @sanctionable_entity = SanctionableEntity.find(params[:id])
  end

  def update
    sanctionable_entity = SanctionableEntity.find(params[:id])
    sanctionable_entity.transaction do
      sanctionable_entity.update!(
        sanctionable_entity_params.merge(
          extra:      sanctionable_entity_extra,
          updater_id: current_user.id,
        )
      )
      sanctionable_entity.fingerprints = FingerprintBuilder.for_entry(sanctionable_entity)
    end
    redirect_to :sanctionable_entities
  end

  def destroy
    @sanctionable_entity = SanctionableEntity.find(params[:id])
    @sanctionable_entity.destroy

    redirect_to :sanctionable_entities
  end

  private

  def sanctionable_entity_params
    params.require(:sanctionable_entity).permit(
      :list_name,
      :official_id,
      :gender,
      :additional_info,
      :extra
    )
  end

  def sanctionable_entity_extra
    @sanctionable_entity_extra ||= JSON.parse(sanctionable_entity_params[:extra].gsub("=>", ": ")).deep_symbolize_keys
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Test App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/sanctionable_entities/_form.html.erb
<div class="container">
  <%= render 'shared/errors', obj: @sanctionable_entity %>
  <%= form_with model: @sanctionable_entity do |form| %>
    <div class="mb-3">
      <%= form.label :list_name, class: "form-label" %><br>
      <%= form.text_field :list_name, class: "form-control" %>
    </div><br>
    <div class="mb-3">
      <%= form.label :official_id, class: "form-label" %><br>
      <%= form.text_field :official_id, class: "form-control" %>
    </div><br>
    <div class="mb-3">
      <%= form.label :gender, class: "form-label" %><br>
      <%= form.text_field :gender, class: "form-control" %>
    </div><br>
    <div class="mb-3">
      <%= form.label :additional_info, class: "form-label" %><br>
      <%= form.text_field :additional_info, class: "form-control" %>
    </div><br>
    <div class="mb-3">
      <%= form.label :extra, class: "form-label" %><br>
      <%= form.text_area :extra, class: "form-control" %>
    </div><br>

    <div class="mb-3"> 
      <%= form.submit class: "btn btn-info btn-lg" %>
    </div>
  <% end %>
</div>

app/views/sanctionable_entities/edit.html.erb
<div class="container">
  <h4>Edit Sanctionable Entity</h4>

  <%= render "form", sanctionable_entity: @sanctionable_entity%>
</div>

app/views/sanctionable_entities/index.html.erb
<div class="container">
  <% if user_signed_in? %>
    <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-outline-danger" %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, class: "btn btn-outline-success" %>
      <%= link_to "Sign in", new_user_session_path, class:"btn btn-outline-primary" %>
  <% end %>
  <br><br>
  
  <h2>Sanctionable Entities</h2>
  <%= link_to "Create", new_sanctionable_entity_path, class: "btn btn-success" %></button>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">ID</th>        
        <th scope="col">Names</th>
        <th scope="col">Gender</th>
        <th scope="col">Birth Dates</th>
      </tr>
    </thead>
    <% @sanctionable_entities.each do |sanctionable_entity| %>
      <tbody>
        <tr>
          <td><%= link_to sanctionable_entity.id, sanctionable_entity %></td>          
          <td><%= sanctionable_entity.extra["name_aliases"]&.map { |n_a| n_a["full_name"] }&.uniq&.join(", ") %></td>
          <td><%= sanctionable_entity.gender %></td>
          <td><%= sanctionable_entity.extra["birth_datas"]&.map { |b_d| b_d["date"] }&.uniq&.join(", ") %></td>
          <td><%= link_to "Edit", edit_sanctionable_entity_path(sanctionable_entity) %></td>
          <td><%= link_to "Destroy", sanctionable_entity_path(sanctionable_entity), method: :delete, data: { confirm: "Are you sure?" } %></td>
        </tr>
      </tbody>
    <% end %> 
  </table>

  <div class="flickr_pagination mb-4">
  <%= will_paginate @sanctionable_entities, :container => false %>
  </div>
</div>

app/views/sanctionable_entities/new.html.erb
<div class="container">
  <h2>New Sanctionable Entity</h2>

  <%= render "form", keyword: @sanctionable_entity%>
</div>

app/views/sanctionable_entities/show.html.erb
<div class="container">
<h2>Sanctionable Person's details</h2>
  <table class="table">
    <tbody>
      <tr>
        <td>List Name</td>
        <td><%= @sanctionable_entity.list_name %></td>
      </tr>
      <tr>
        <td>Official Id</td>
        <td><%= @sanctionable_entity.official_id %></td>
      </tr>
      <tr>
        <td>Additional Info</td>
        <td><%= @sanctionable_entity.additional_info %></td>
      </tr>
      <tr>
        <td>Gender</td>
        <td><%= @sanctionable_entity.gender %></td>
      </tr>
       <tr>
        <td>Extra</td>
        <td><%= @sanctionable_entity.extra %></td>
      </tr>
      <tr>
        <td>Created At</td>
        <td><%= @sanctionable_entity.created_at %></td>
      </tr>
      <tr>
        <td>Creator Id</td>
        <td><%= @sanctionable_entity.creator_id %></td>
      </tr>
      <tr>
        <td>Updated At</td>
        <td><%= @sanctionable_entity.updated_at %></td>
      </tr>
      <tr>
        <td>Updater Id</td>
        <td><%= @sanctionable_entity.updater_id %></td>
      </tr>

    </tbody>
  </table>

  <%= link_to "Edit", edit_sanctionable_entity_path(@sanctionable_entity), class: "btn btn-outline-info" %></button>
  <%= link_to "Destroy", sanctionable_entity_path(@sanctionable_entity), class: "btn btn-outline-danger", method: :delete, data: { confirm: "Are you sure?" } %>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/index.html.erb
<div class="container">
  <h2>Users</h2>
  <ul>
    <% @users.each do |user| %>
      <li>
        <%= link_to user.email, users_path %>
      </li>
    <% end %>  
  </ul>
</div>